### ISSUE TITLE
Latest update - bottle volume selection 3 decimal places

### ISSUE THREAD

**Issue by Cabarnacus** [babybuddy/babybuddy-for-android#73]
Latest update from play store has the feed volume selection to 3 decimal places which makes selecting volume on touch screen quite fiddly/difficult.

![Screenshot_2024-05-16-09-04-18-43_362529e8c6da8af85c01888406643b2b](https://github.com/babybuddy/babybuddy-for-android/assets/92682977/7a1f7d6c-afe2-4e93-bc78-d5996672a30c)

**Comment by MrApplejuice** [comment]
Hey, thank you for reporting!

I am about to change the way the interface works all together because the current swipe-based scroll thing does not work well with the children selection and also does not allow entering a value manually. The entire thing will be exchanged for "spinner buttons" that should do a lot better when it comes to selecting exact values. The change will take a few more weeks to develop though...

**Comment by OneCreek** [comment]
Looking much better in https://github.com/babybuddy/babybuddy-for-android/issues/74#issuecomment-2324150032 v2.4.0 release candidate:)

**Comment by MrApplejuice** [comment]
Took a long time, but I am glad you stuck around! A few more finishing touches, and the new version can go live. Sorry for the huge delay, it took quite some time to get this right. Lots of internal updates.

**Comment by MrApplejuice** [comment]
Scheduled for release in v2.4.0. Too tired now. I will try to ship it tomorrow!
