### ISSUE TITLE
Error: Date/time can not be in the future

### ISSUE THREAD

**Issue by OneCreek** [babybuddy/babybuddy-for-android#77]
Hello @MrApplejuice ,

When storing a diaper change in v2.4.0, I sometimes get the error message
![cc63e6ec-adc7-4793-b8cc-3a64dedb87d1.jpg](https://github.com/user-attachments/assets/36798791-d88e-47ae-b4fa-514e564cc17d)

"Could not store activity
Error while storing activity
Server reported: Date/time can not be in the future."

Any idea where this is coming from? Didn't happen in the previous stable version.
I also sent a "contact developer" through the app.

Thanks:)

**Comment by MrApplejuice** [comment]
Hey. Thank you for reporting. I got your messages earlier today, but only now found some time to book them... but it seems you already did it yourself, thanks for that.

This bug falls squarely into the category that I already know a bit about: The new interface was not quite finished when I released it. I think something goes wrong with the retry and/or server-synchronization logic here. Getting out the new interface after the total failure of the event history seemed a lot more pressing though, so it did not get a good polish yet.

How severe is it? I hope that this only pops up _sometimes_ and that this does not fully block your workflow right now?

**Comment by OneCreek** [comment]
> Getting out the new interface after the total failure of the event history seemed a lot more pressing though, so it did not get a good polish yet.

Absolutely the right decision! 

> How severe is it? I hope that this only pops up _sometimes_ and that this does not fully block your workflow right now?

No not severe. Not super rare but definitely something one can accept temporarily. Maybe 1 out of 5 times... Roughly... Just wanted to let you know and give you some information about it for trouble shooting.

**Comment by MrApplejuice** [comment]
> No not severe. Not super rare but definitely something one can accept temporarily

Ok... thanks for the update on this then. This sounds more like a bugfix then. Definitely an easier task than rewriting the user interface, so I expect to be able to fix this soon-ish. Stay tuned! :wink:

**Comment by MrApplejuice** [comment]
Spent this weekend to trace the bug. The reason why this is happening _is_ due to having rushed the release, but unfortunately the fix is not super-trivial. The new babybuddy API interface uses a more robust server interface based on the `retrofit`-library, which indeed proved to be more robust by immediately fixing #74 without much extra work. However, because of the rush-to-the-finish, I forgot about a few elements that the _old_ server interface did:

- The old server interface tried to keep track of the server-clock <-> client-clock difference and correct for timing differences.
- The old server interface did implement graceful retries with exponential backoff, which the new interface does not do.

These need to be re-implemented. Ideally, the re-implementation will be replacing more parts of the old implementation. Already started to work on this, but it will take a little bit longer.

**Comment by OneCreek** [comment]
Thanks for the update!

**Comment by MrApplejuice** [comment]
About time for an update: Nothing happened for the past 2 weeks, because I got ill. I then had to catch up with some tasks that are not open source work, but I am back at this now!

**Comment by MrApplejuice** [comment]
New bugfix is live, already available here on GitHub, and should also become available on the Google App Store later today!

**Comment by MrApplejuice** [comment]
Aaand... it will not be on the app store today. For some reason my newest update was rejected due to "sexual content or profanity". So this update goes into the prolonged review cycle...

**Comment by MrApplejuice** [comment]
Appeal is still in the processing queue... no updates yet.

**Comment by OneCreek** [comment]
Maybe due to beta testing... But I think I got the latest version in Google play store already since a couple of days:
![Screenshot_20241009-224731.png](https://github.com/user-attachments/assets/f054073a-21c6-44f9-b660-b89b10227996)

**Comment by MrApplejuice** [comment]
Ah yes, thanks, I forgot that the rollout for open testing was successful! So yes, this is a way to have 2.4.2 from the play store, should anyone else want it already. Full roll-out into production is still blocked though:

![image](https://github.com/user-attachments/assets/744211ca-f9ce-4d18-9f3f-b148666899b8)

Also: For subsequent releases I need to fix my policy standing first. So the appeal needs to be processed before I can book any more progress on the app itself...

**Comment by MrApplejuice** [comment]
I received multiple messages from Android users that this problem persists. This _was true_ because Google rejected my app update because of #86. It took ages for Google to respond to my appeal and with a minor change to the breast feeding image it seems to finally be fixed.

This means that Android users can enjoy the same fixes as the github version users.

**Comment by OneCreek** [comment]
> It took ages for Google to respond to my appeal and with a minor change to the breast feeding image it seems to finally be fixed.

What a painful struggle... Glad it got cleared out finally! Thanks for your patience:D
